system:
  ip: 127.0.0.1
  port: 8081
  gin_mode: debug
  env: "dev"
log:
  app: blog_server
  dir: ./logs
  level: debug   # debug/info/warn/error
db:
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  db_name: blog
  debug: true
  source: mysql
jwt:
  expire: 24
  secret: your-generated-base64-string-here
  issuer: iflmayu
redis:
  host: 127.0.0.1
  port: 6379
  password: 1234
  db: 0
upload:
  max_size: 5              # MB
  allowed_types:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .webp
  upload_dir: images
storage:
  type: qiniu      # local 或 qiniu
  local:
    root_path: ./uploads
    base_url: http://127.0.0.1:8081
  qiniu:
    access_key: wUlX7B_fyoaSbHwU18yZY76OBrwnQWaqcxZPk48d
    secret_key: zsLomNgxi8GuKSKeNY0Uv1LDdYnfNzHQLHHPGt5j
    bucket: iflmayu2
    domain: http://tgm9arffj.hn-bkt.clouddn.com